# Generated by Django 5.2.7 on 2025-10-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='neto',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='tot_des',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='tot_ing',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
