# Generated by Django 5.2.7 on 2025-10-26 02:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina_app', '0002_alter_nomina_neto_alter_nomina_tot_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='tot_des',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='tot_ing',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='iess',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='neto',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='tot_des',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nominadetalle',
            name='tot_ing',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
