# Generated by Django 5.2.7 on 2025-10-25 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSobretiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sobretiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('numero_horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina_app.empleado')),
                ('tipo_sobretiempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sbtemp_app.tiposobretiempo')),
            ],
        ),
    ]
